[package]
name = "egui_vulkano_backend"
version = "0.4.1"
authors = ["t18b219k <t18b219k@mail.cc.niigata-u.ac.jp>"]
edition = "2018"
license="MIT OR Apache-2.0"
description = "Backend code to use egui with vulkano."
homepage = "https://github.com/t18b219k/egui_vulkano_backend"
repository = "https://github.com/t18b219k/egui_vulkano_backend"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
backend_debug=[]
[dependencies]
vulkano = "^0.23.0"
epi = "0.12.0"
iter_vec ="0.1"
[dev-dependencies]
egui_winit_platform = "0.7.0"
epi_http={version="0.12.0"}
egui="0.12.0"
epi={version="0.12.0",features=["http"]}
winit="0.24.0"
egui_demo_lib = {version="0.12.0",features=["http","syntect"]}
vulkano-win = "^0.23.0"
ffmpeg ={version="0.3"}
chrono ="0.4.19"